# Generated by Django 5.1 on 2024-08-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_videos_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('cover', models.CharField(max_length=500)),
                ('ratings', models.BigIntegerField()),
                ('reviews', models.TextField()),
                ('available', models.TextField()),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
