# Generated by Django 5.1 on 2024-08-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
