# Generated by Django 5.1 on 2024-08-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
