# Generated by Django 5.1 on 2024-08-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=500)),
                ('likes', models.BigIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
