# Generated by Django 5.1 on 2024-08-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=50)),
                ('ratings', models.FloatField()),
                ('img', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('purchaseLink', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings',
            field=models.FloatField(),
        ),
    ]
