# Generated by Django 5.1 on 2024-08-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_course_alter_book_ratings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
