# Generated by Django 5.1 on 2024-08-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
