# Generated by Django 5.0.1 on 2024-09-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_review_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
